---

- name: Copy central config file
  win_template:
    src: nsclient_central.ini.j2
    dest: '{{ nsclient_central_config_path }}\nsclient_central.ini'
  when: '"nsclient-fileserver" in group_names'

- name: Copy powershell scripts
  win_copy:
    src: scripts
    dest: '{{ nsclient_central_config_path }}'
  when: '"nsclient-fileserver" in group_names'

- name: Create temp dir
  win_file:
    path: C:\tmp\
    state: directory

- name: Transfer nsclient
  win_copy:
    src: nsclient.msi
    dest: C:\tmp\nsclient.msi

- name: Install NSclient
  win_package:
    path: C:\tmp\nsclient.msi
    state: present

- name: Copy local config file
  win_template:
    src: nsclient_local.ini.j2
    dest: C:\Program Files\NSClient++\nsclient.ini

- name: Allow nsclient in Windows firewall
  win_firewall_rule:
    name: NSClient
    localport: '{{ nsclient_port }}'
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Allow ping in in Windows firewall
  win_firewall_rule:
    name: Allow ping
    localport: any
    action: allow
    direction: in
    protocol: ICMPv4
    state: present
    enabled: yes

# SeServiceLogonRight: gives permission to log on as service
- name: Grant SeServiceLogonRight to nsclient user
  win_user_right:
    name: SeServiceLogonRight
    users:
    - '{{ nsclient_user }}'
    action: add

# This is not optimal, but is the only way I know at the moment to make lasinstwinupdates to run properly
- name: Add nsclient@kc.local to local administrators group on target host
  win_group_membership:
    name: Administrators
    members:
    - '{{ nsclient_user }}'
    state: present

# # SeSystemProfilePrivilege: gives permission to gather system performance data (needed for the lastinstwinupdates check)
# - name: Add neccessary privilegies to nsclient user
#   win_user_right:
#     name: SeSystemProfilePrivilege
#     users:
#     - '{{ nsclient_user }}'
#     action: add
#
# - name: Add neccessary privilegies to nsclient user (SeProfileSingleProcessPrivilege)
#   win_user_right:
#     name: SeProfileSingleProcessPrivilege
#     users:
#     - '{{ nsclient_user }}'
#     action: add

- name: Restart NSClient service
  win_service:
    name: nscp
    username: '{{ nsclient_user }}'
    password: '{{ nsclient_password }}'
    state: restarted
    start_mode: auto
